name: TestNetwork
on: push

jobs:
  test_projects:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        python -m pip install Pillow
        python3 manage.py makemigrations
        python3 manage.py migrate
        python3 manage.py test network